### ISSUE TITLE
Android display issue with hyper link

### ISSUE THREAD

**Issue by dbof10** [jsdf/react-native-htmlview#176]
Given a html text ```
I shared some of my (perhaps terrible) <a href=\"https://twitter.com/rrhoover/status/924678180073455617\">ideas on Twitter</a> earlier today```.  

Result
![screen shot 2017-11-05 at 11 00 11 am](https://user-images.githubusercontent.com/10725747/32411854-921cbab4-c218-11e7-99e7-04f5f62c96c2.png)

The hyper link takes up one line.

Expected result
The hyper link is inline with other texts

**Comment by tinchoz49** [comment]
Hi everyone! what is the status of this issue? I'm having the same problem

**Comment by dbof10** [comment]
No update

**Comment by isilher** [comment]
Did you try wrapping the surrounding text in a `<div>` or `<p>` tag?

**Comment by dbof10** [comment]
Is there a better way to address this since html comes from server?. I don't have control

**Comment by rajasaur** [comment]
@dbof10 : I havent tried this but when debugging my problem , I found that without a `<div>` or `<p>` (or any top-level element), it broke a text like
`This is a test <a href='....'>....</a>some more`
into three nodes ("This is a test", contents of a tag and "some more"). This probably explains why each part of it is shown separately with a line break between them.

Maybe you could implement the renderNode function and if the nodeName == 'a', then write your custom style into it instead of using the default style ? https://github.com/jsdf/react-native-htmlview#custom-element-rendering

**Comment by dbof10** [comment]
I agree with custom renderer. However, `<a>` is for hyperlink. It should be inline. The library should support this behavior by default.

**Comment by isilher** [comment]
Currently, the library expects valid HTML, meaning it should be wrapped in a single top level tag. Not doing so will break lines for all first level tags (not just `<a>`) as the RootComponent default is a View (not inline styled).
If you have no control over the source, you could wrap `value` before passing it to the HTMLView component:

``` jsx
<HTMLView
  value={`<div>${value}</div>`}
  stylesheet={stylesheet}
/>
```

**Comment by dbof10** [comment]
That's valid. Thanks
