### ISSUE TITLE
li margin/padding not works

### ISSUE THREAD

**Issue by igorlaunch** [jsdf/react-native-htmlview#205]
I am having \<li\> tags inside \<ol\> and want to give some margin between the \<li\> tags.
I tried 
```
htmlStyle = StyleSheet.create({
   li: {
      marginTop: 20
   }
});
```
But this not works
Anybody knows how to solve this?

**Comment by isilher** [comment]
Hi @igorlaunch, margins and paddings require block styling (versus the inline styling required to make the nested html markup work). Sadly at this moment it is not possible to combine both because of limitations in React Native for android (See also #111).

For iOS only suggestions to apply styling to list elements, see comments in #172.
