### ISSUE TITLE
Change default style of view

### ISSUE THREAD

**Issue by lukakerr** [jsdf/react-native-htmlview#208]
Is there a way to change the default style of the view? If no element is included in the HTML (i.e. just plain text), there doesn't seem to be a way to add styling. What would be ideal would be if there was a way to style the `body` of the view as if it's normal HTML, and these styles would apply globally to the view, but would be overridden by more specific selectors

**Comment by isilher** [comment]
Hi @lukakerr, plain text will not receive any of the default or custom HTML styling because it's not wrapped in any HTML tag. If you wrap your text in a `<div>` or `<p>` tag before passing it to the library it should get all default styling supplied.

If this does not solve your problem, please supply an example code snippet and the expected result.

**Comment by lukakerr** [comment]
Ah yep doing `<body>{htmlContent}</body>` seems to work, thanks
