### ISSUE TITLE
use htmlview onLinkPress error

### ISSUE THREAD

**Issue by xifumengmengda** [jsdf/react-native-htmlview#45]
![222](https://cloud.githubusercontent.com/assets/16473366/18736363/f68f17c8-80b8-11e6-8828-624757abddda.png)
when i want to click like <a href='http://www.baidu.com'></a>  and error like the picture ,and my code like this 
![333](https://cloud.githubusercontent.com/assets/16473366/18736411/63e83886-80b9-11e6-89f5-6cdf55981ada.png)
![444](https://cloud.githubusercontent.com/assets/16473366/18736421/6d5fd9aa-80b9-11e6-9d6a-40d0185ee051.png)
so  what should i do ?

**Comment by samparmenter** [comment]
The issue is in the Linking.js react-native class which is calling this._validateURL in the Linking.openURL function. By default the HTMLView sets Linking.openURL as the click handler and simply calls it when a link is pressed. At that point however, `this` refers to the options object (you need to look at HTMLView source to see this) and as that object doesn't have a _validateURL function it throws the error. 

An easy way around this is to override the onLinkPress property like below which ensures that `this` refers to the class Linking instead of the opts object.

`<HTMLView
          value={blurb}
          onLinkPress={(url) => Linking.openURL.call(Linking, url)}
        />`

**Comment by chandlervdw** [comment]
@samparmenter thanks for the explanation and fix.
