### ISSUE TITLE
Inline style not supported.

### ISSUE THREAD

**Issue by jatazoulja** [jsdf/react-native-htmlview#56]
Could not render inline style attribute?
`<div dir="ltr" style="text-decoration: underline; font-weight: bold; font-style: italic;">`

**Comment by Kaishley** [comment]
bump @jsdf

**Comment by Unforgiven-wanda** [comment]
Bump here as well.

**Comment by KClough** [comment]
Bumpity bump bump.

**Comment by richchurcher** [comment]
At this stage I'm going to say this is a won't fix... I think it makes more sense to keep the styles in the component rather than the HTML. You could potentially strip the styles out in a parent component and process them using [css-to-react-native](https://github.com/styled-components/css-to-react-native) if desired.
